# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Run `pre-commit install` to activate pre-commit hooks
repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
    - id: markdownlint-cli2
  - repo: 'https://github.com/facelessuser/pyspelling.git'
    rev: '2.12.1'
    hooks:
      - id: 'pyspelling'
        args: [
          "--config", ".spellcheck.yaml"
        ]
